name: CustomCMD
version: 1.1
author: SanyaSho
api-version: 1.16
main: me.sanyasho.custommodeldata.CMDMain
description: Custom CMD plugin. Special for ProjectT29
commands:
    custommodeldata:
        usage: /<command> [int]
        description: Set CustomModelData
        aliases: [cmd, customcmd, ccmd, cusmoddat]
