name: CustomCMD
version: 1.2
author: SanyaSho
api-version: 1.16
main: me.sanyasho.custommodeldata.CMDMain
description: Custom CMD plugin. Special for ProjectT29
commands:
    custommodeldata:
        usage: /<command> [int]
        description: Set CustomModelData
        aliases: [cmd, customcmd, ccmd, cusmoddat]
        permission: cmd.use
    cmdreload:
        usage: /<command>
        description: Reload config
        permission: cmd.reload
permissions:
    cmd.use:
        description: Permission for /custommodeldata
    cmd.reload:
        description: Permission for /cmdreload
